[profile.default]
src = "contracts"
out = "forge-out"
libs = ["lib"]
test = "test/foundry"
solc = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

[profile.default.fuzz]
runs = 256
